### ISSUE TITLE
HI! Here is problem. After few time or random action  VUSB is gone.

### ISSUE THREAD

**Issue by brutevinch** [tosiara/usbasp-gpio#1]
Can you help me? May be i use wrong fuses? How i can flash this firmware correctly using avrdude? Other firmware for example USBtemp works good. My email brutevinch@icloud.com. Hope you can write to me.

**Comment by tosiara** [comment]
What kind of USBasp do you have? You should flash hex file as regular firmware, no special actions:

```
avrdude -c usbasp -p m8 -U flash:w:firmware.hex
```

**Comment by brutevinch** [comment]
i've got this:  http://www.ebay.com/itm/New-1pc-USB-ISP-Programmer-For-ATMEL-AVR-ATMega-ATTiny-51-Development-Board-/400596661681?hash=item5d456bf5b1

**Comment by tosiara** [comment]
What error do you get when you flash the firmware?

**Comment by brutevinch** [comment]
There is no error. Firmware flashes ok. Then i reconnect usbasp. lsusb shows me VUSB device....looks like everything is ok but after random time 1-5-3 min device gone.

**Comment by tosiara** [comment]
Paste the log how that looks like, what do you mean by "gone"

**Comment by brutevinch** [comment]
I don't know how but now all works fine. Sorry for disturb!

**Comment by tosiara** [comment]
No problem

**Comment by brutevinch** [comment]
Oh..... after hour i've got Could not find USB device "usbgpio" with vid=0x16c0 pid=0x5dc

**Comment by tosiara** [comment]
Paste your dmesg/syslog/journalctl output

**Comment by brutevinch** [comment]
SYSLOG

Sep 21 16:39:25 devboard kernel: [ 4823.668850] usb 1-1.4: Manufacturer: homes-smart.ru
Sep 21 16:39:25 devboard kernel: [ 4824.328055] usb 1-1.4: USB disconnect, device number 51
Sep 21 16:39:26 devboard kernel: [ 4825.153754] usb 1-1.4: new low-speed USB device number 52 using dwc_otg
Sep 21 16:39:26 devboard kernel: [ 4825.278672] usb 1-1.4: New USB device found, idVendor=16c0, idProduct=05dc
Sep 21 16:39:26 devboard kernel: [ 4825.278714] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Sep 21 16:39:26 devboard kernel: [ 4825.278737] usb 1-1.4: Product: usbgpio
Sep 21 16:39:26 devboard kernel: [ 4825.278754] usb 1-1.4: Manufacturer: homes-smart.ru
Sep 21 16:39:27 devboard kernel: [ 4825.608245] usb 1-1.4: USB disconnect, device number 52
Sep 21 16:39:28 devboard kernel: [ 4826.863781] usb 1-1.4: new low-speed USB device number 53 using dwc_otg
Sep 21 16:39:28 devboard kernel: [ 4826.987600] usb 1-1.4: New USB device found, idVendor=16c0, idProduct=05dc
Sep 21 16:39:28 devboard kernel: [ 4826.987642] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Sep 21 16:39:28 devboard kernel: [ 4826.987662] usb 1-1.4: Product: usbgpio
Sep 21 16:39:28 devboard kernel: [ 4826.987680] usb 1-1.4: Manufacturer: homes-smart.ru
Sep 21 16:39:29 devboard kernel: [ 4827.656512] usb 1-1.4: USB disconnect, device number 53
Sep 21 16:39:30 devboard kernel: [ 4828.913806] usb 1-1.4: new low-speed USB device number 54 using dwc_otg
Sep 21 16:39:30 devboard kernel: [ 4829.037751] usb 1-1.4: New USB device found, idVendor=16c0, idProduct=05dc
Sep 21 16:39:30 devboard kernel: [ 4829.037792] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Sep 21 16:39:30 devboard kernel: [ 4829.037812] usb 1-1.4: Product: usbgpio
Sep 21 16:39:30 devboard kernel: [ 4829.037830] usb 1-1.4: Manufacturer: homes-smart.ru
Sep 21 16:39:31 devboard kernel: [ 4829.960810] usb 1-1.4: USB disconnect, device number 54
Sep 21 16:39:32 devboard kernel: [ 4831.223836] usb 1-1.4: new low-speed USB device number 55 using dwc_otg
Sep 21 16:39:32 devboard kernel: [ 4831.349063] usb 1-1.4: New USB device found, idVendor=16c0, idProduct=05dc
Sep 21 16:39:32 devboard kernel: [ 4831.349103] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Sep 21 16:39:32 devboard kernel: [ 4831.349124] usb 1-1.4: Product: usbgpio
Sep 21 16:39:32 devboard kernel: [ 4831.349140] usb 1-1.4: Manufacturer: homes-smart.ru
Sep 21 16:39:33 devboard kernel: [ 4831.753038] usb 1-1.4: USB disconnect, device number 55
Sep 21 16:39:34 devboard kernel: [ 4833.263858] usb 1-1.4: new low-speed USB device number 56 using dwc_otg
Sep 21 16:39:34 devboard kernel: [ 4833.387473] usb 1-1.4: New USB device found, idVendor=16c0, idProduct=05dc
Sep 21 16:39:34 devboard kernel: [ 4833.387514] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Sep 21 16:39:34 devboard kernel: [ 4833.387534] usb 1-1.4: Product: usbgpio
Sep 21 16:39:34 devboard kernel: [ 4833.387551] usb 1-1.4: Manufacturer: homes-smart.ru
Sep 21 16:39:36 devboard kernel: [ 4834.825452] usb 1-1.4: USB disconnect, device number 56
Sep 21 16:39:37 devboard kernel: [ 4836.163890] usb 1-1.4: new low-speed USB device number 57 using dwc_otg
Sep 21 16:39:37 devboard kernel: [ 4836.288749] usb 1-1.4: New USB device found, idVendor=16c0, idProduct=05dc
Sep 21 16:39:37 devboard kernel: [ 4836.288791] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Sep 21 16:39:37 devboard kernel: [ 4836.288810] usb 1-1.4: Product: usbgpio
Sep 21 16:39:37 devboard kernel: [ 4836.288828] usb 1-1.4: Manufacturer: homes-smart.ru
Sep 21 16:39:38 devboard kernel: [ 4836.873728] usb 1-1.4: USB disconnect, device number 57
Sep 21 16:39:39 devboard kernel: [ 4838.173914] usb 1-1.4: new low-speed USB device number 58 using dwc_otg
Sep 21 16:39:39 devboard kernel: [ 4838.300034] usb 1-1.4: New USB device found, idVendor=16c0, idProduct=05dc
Sep 21 16:39:39 devboard kernel: [ 4838.300075] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Sep 21 16:39:39 devboard kernel: [ 4838.300095] usb 1-1.4: Product: usbgpio
Sep 21 16:39:39 devboard kernel: [ 4838.300113] usb 1-1.4: Manufacturer: homes-smart.ru
Sep 21 16:39:40 devboard kernel: [ 4838.666007] usb 1-1.4: USB disconnect, device number 58

DMESG

[ 4905.114750] usb 1-1.4: new low-speed USB device number 87 using dwc_otg
[ 4905.239852] usb 1-1.4: New USB device found, idVendor=16c0, idProduct=05dc
[ 4905.239894] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 4905.239913] usb 1-1.4: Product: usbgpio
[ 4905.239931] usb 1-1.4: Manufacturer: homes-smart.ru
[ 4905.491069] usb 1-1.4: USB disconnect, device number 87
[ 4906.754747] usb 1-1.4: new low-speed USB device number 88 using dwc_otg
[ 4906.879950] usb 1-1.4: New USB device found, idVendor=16c0, idProduct=05dc
[ 4906.879991] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 4906.880011] usb 1-1.4: Product: usbgpio
[ 4906.880027] usb 1-1.4: Manufacturer: homes-smart.ru
[ 4907.027289] usb 1-1.4: USB disconnect, device number 88
[ 4908.544747] usb 1-1.4: new low-speed USB device number 89 using dwc_otg
[ 4908.669691] usb 1-1.4: New USB device found, idVendor=16c0, idProduct=05dc
[ 4908.669731] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 4908.669750] usb 1-1.4: Product: usbgpio
[ 4908.669767] usb 1-1.4: Manufacturer: homes-smart.ru
[ 4908.819534] usb 1-1.4: USB disconnect, device number 89
[ 4910.334766] usb 1-1.4: new low-speed USB device number 90 using dwc_otg
[ 4910.458822] usb 1-1.4: New USB device found, idVendor=16c0, idProduct=05dc
[ 4910.458864] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 4910.458883] usb 1-1.4: Product: usbgpio
[ 4910.458900] usb 1-1.4: Manufacturer: homes-smart.ru
[ 4910.867743] usb 1-1.4: USB disconnect, device number 90
[ 4912.124827] usb 1-1.4: new low-speed USB device number 91 using dwc_otg
[ 4912.624815] usb 1-1.4: device not accepting address 91, error -32
[ 4913.444849] usb 1-1.4: new low-speed USB device number 93 using dwc_otg
[ 4913.569892] usb 1-1.4: New USB device found, idVendor=16c0, idProduct=05dc
[ 4913.569934] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 4913.569954] usb 1-1.4: Product: usbgpio
[ 4913.569973] usb 1-1.4: Manufacturer: homes-smart.ru
[ 4913.940236] usb 1-1.4: USB disconnect, device number 93
[ 4915.194879] usb 1-1.4: new low-speed USB device number 94 using dwc_otg
[ 4915.318598] usb 1-1.4: New USB device found, idVendor=16c0, idProduct=05dc
[ 4915.318640] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 4915.318660] usb 1-1.4: Product: usbgpio
[ 4915.318678] usb 1-1.4: Manufacturer: homes-smart.ru
[ 4915.732473] usb 1-1.4: USB disconnect, device number 94
[ 4917.074858] usb 1-1.4: new low-speed USB device number 95 using dwc_otg
[ 4917.199357] usb 1-1.4: New USB device found, idVendor=16c0, idProduct=05dc
[ 4917.199397] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 4917.199417] usb 1-1.4: Product: usbgpio
[ 4917.199434] usb 1-1.4: Manufacturer: homes-smart.ru
[ 4917.524710] usb 1-1.4: USB disconnect, device number 95
[ 4918.784879] usb 1-1.4: new low-speed USB device number 96 using dwc_otg
[ 4918.910642] usb 1-1.4: New USB device found, idVendor=16c0, idProduct=05dc
[ 4918.910686] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 4918.910709] usb 1-1.4: Product: usbgpio
[ 4918.910726] usb 1-1.4: Manufacturer: homes-smart.ru

**Comment by brutevinch** [comment]
it's random works

root@devboard /opt/Sources/USBASP/GPIO-USB/commandline # ./gpio-usb status
LED 1 is off
LED 2 is off
LED 3 is off
LED 4 is off
LED 5 is on
LED 6 is off
LED 7 is off
LED 8 is off
root@devboard /opt/Sources/USBASP/GPIO-USB/commandline # ./gpio-usb status
Could not find USB device "usbgpio" with vid=0x16c0 pid=0x5dc
root@devboard /opt/Sources/USBASP/GPIO-USB/commandline # ./gpio-usb status
Could not find USB device "usbgpio" with vid=0x16c0 pid=0x5dc
root@devboard /opt/Sources/USBASP/GPIO-USB/commandline # ./gpio-usb status
Could not find USB device "usbgpio" with vid=0x16c0 pid=0x5dc
root@devboard /opt/Sources/USBASP/GPIO-USB/commandline # ./gpio-usb status
LED 1 is off
LED 2 is off
LED 3 is off
LED 4 is off
LED 5 is on
LED 6 is off
LED 7 is off
LED 8 is off

**Comment by brutevinch** [comment]
tried this on iMac and RPI result the same.

**Comment by tosiara** [comment]
It looks more like hardware issue - usbasp or usb port. Can you try more computers? Any laptop and workstation?

**Comment by brutevinch** [comment]
now i make this test: enable two leds on usbasp "./gpio on 1 and ./gpio on 2" and wait....leds are power off.  it looks like problem not with usb. it's like usbasp reboots

**Comment by tosiara** [comment]
Have ever resolved your issue?

**Comment by brutevinch** [comment]
hi, it's no more actual. Thank you
