### ISSUE TITLE
segfault on MIPS

### ISSUE THREAD

**Issue by adfnekc** [tosiara/usbasp-gpio#13]
First of all, sorry for asking you a question in this wrong place. I saw your question about "segfault on MIPS" on the link [https://github.com/AlexanderOMara/wireguard-go-builds/issues/1](url) and I had the same problem. I compiled the binary for the mips platform using the go language and when I put it on my mips host to run it, it gave me an error, exactly like the one you raised.
My environment is 

- x86_64 linux 
- kernel 4.19 
- go 1.15.6

using ```GOOS=linux GOARCH=mips go build```

**Comment by tosiara** [comment]
Sorry, I did not solve that and could not help you
